# Generated by Django 3.1.3 on 2020-11-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.CharField(default=0.05, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='ibu',
            field=models.CharField(default=60, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='ounces',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.CharField(default='Cider', max_length=200),
            preserve_default=False,
        ),
    ]
